/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_vremenska_MyNDK */

#ifndef _Included_com_example_vremenska_MyNDK
#define _Included_com_example_vremenska_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_vremenska_MyNDK
 * Method:    conversion
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_vremenska_MyNDK_conversion
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
